default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: waroong_development

test:
  <<: *default
  database: waroong_test


production:
  <<: *default
  database: waroong_production
  username: waroong
  password: <%= ENV['WAROONG_DATABASE_PASSWORD'] %>
